on:
  push:
    branches:
      - main
jobs:
  on-commit:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: 'sample.p13n/package-lock.json'

      - name: Install and build examples
        run: |
          mkdir gh-pages
          zip -r gh-pages/p13n.tutorial.zip exercises/ex01/sample.p13n

          cd gh-pages
          mkdir exercises
          for dir in ../exercises/ex*; do
              cd "$dir"/sample.p13n
              npm install
              npm run build
              echo "$dir"
              mv dist "$dir"/sample.p13n/
          done
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages